controllers:
    resource: ../src/Controller/
    type: attribute
    
admin_login:
    path: /admin/login
    controller: App\Controller\AdminSecurityController::login

admin_logout:
    path: /admin/logout
    controller: App\Controller\AdminSecurityController::logout

homepage:
    path: /
    controller: App\Controller\MainController::index

