controllers:
    resource: ../src/Controller/
    type: attribute
    
# app_login:
#     path: /Admin/login
#     controller: App\Controller\SecurityController::login

# app_logout:
#     path: /Admin/logout
#     controller: App\Controller\SecurityController::logout

homepage:
    path: /
    controller: App\Controller\MainController::index

